// <auto-generated />
using System;
using MNApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MNApp.DAL.Migrations
{
    [DbContext(typeof(MNAppDBContext))]
    [Migration("20210423204455_DomainDetailAdded")]
    partial class DomainDetailAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MNApp.DAL.DomainDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ExpiryAt");

                    b.Property<int>("FileDetailId");

                    b.Property<bool?>("HasContact");

                    b.Property<bool?>("HasDate");

                    b.Property<bool?>("HasMail");

                    b.Property<bool?>("HasMedia");

                    b.Property<string>("IPAddress");

                    b.Property<bool?>("IsPing");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("RegisterAt");

                    b.Property<DateTime?>("UpdateAt");

                    b.HasKey("Id");

                    b.HasIndex("FileDetailId");

                    b.ToTable("DomainDetails");
                });

            modelBuilder.Entity("MNApp.DAL.FileDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FileDetails");
                });

            modelBuilder.Entity("MNApp.DAL.DomainDetail", b =>
                {
                    b.HasOne("MNApp.DAL.FileDetail", "FileDetail")
                        .WithMany("DomainDetails")
                        .HasForeignKey("FileDetailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
